<?php

namespace Database\Seeders;

use App\Models\Post;
use App\Models\User;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class PostSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Post::upsert([
            [
                'topic_id' => 1,
                'author_id' => 1,
                'title' => 'What makes medieval feudalism so appealing in fantasy settings?',
                'description' => 'I’ve noticed many fantasy games and stories lean into feudal structures. Is it the drama, the hierarchy, or the knights? What do you all think?',
                'share_count' => 18,
                // created_at sama updated_at pakai factory buat di randomkan biar gak sama semua tlg marco
            ],
            [
                'topic_id' => 2,
                'author_id' => 2,
                'title' => 'Why Frieren is a masterpiece in slow-paced storytelling',
                'description' => 'Just finished episode 20 and I’m in awe. The quiet depth, the emotional beats… this series is something special. Anyone else feel the same?',
                'share_count' => 29,
            ],
            [
                'topic_id' => 3,
                'author_id' => 3,
                'title' => 'What are your go-to 15-minute meals that don’t feel like fast food?',
                'description' => 'I’m trying to cut down on takeout. Would love to see some quick, healthy, and genuinely satisfying meals the community enjoys.',
                'share_count' => 21,
            ],
            [
                'topic_id' => 4,
                'author_id' => 4,
                'title' => 'The best “no-budget” cosplay you’ve seen or made?',
                'description' => 'Creativity often shines brightest with limitations. Show off your DIY cosplay hacks and resourceful builds!',
                'share_count' => 13,
            ],
            [
                'topic_id' => 5,
                'author_id' => 5,
                'title' => 'Does journaling really improve mental clarity?',
                'description' => 'I’ve heard tons of advice saying that writing your thoughts down helps with stress and focus. For those who do it, has it helped?',
                'share_count' => 17,
            ],
            [
                'topic_id' => 6,
                'author_id' => 6,
                'title' => 'Most underrated 90s anime that deserves a reboot?',
                'description' => 'Everyone talks about Evangelion and Sailor Moon, but what are the hidden gems that newer fans have probably missed?',
                'share_count' => 26,
            ],
            [
                'topic_id' => 7,
                'author_id' => 7,
                'title' => 'How did your parents shape your relationship with money?',
                'description' => 'Let’s talk upbringing and finance. What lessons (or traumas 😅) did your household financial habits leave you with?',
                'share_count' => 20,
            ],
            [
                'topic_id' => 8,
                'author_id' => 8,
                'title' => 'What made Code Geass so addicting?',
                'description' => 'I binged it in 3 days. Was it the chess-like plot? Lelouch’s charisma? The moral grey areas? Share your take!',
                'share_count' => 31,
            ],
            [
                'topic_id' => 9,
                'author_id' => 9,
                'title' => 'Let’s talk about daily digital routines — what keeps you sane?',
                'description' => 'Between work, news, and social media, how do you structure your screen time without losing your mind?',
                'share_count' => 15,
            ],
            [
                'topic_id' => 10,
                'author_id' => 10,
                'title' => 'Studio Ghibli vs. Makoto Shinkai — who nails emotional resonance better?',
                'description' => 'Both studios have their strengths, but if you had to pick based purely on emotional storytelling, who gets your vote?',
                'share_count' => 28,
            ],
            [
                'topic_id' => 11,
                'author_id' => 11,
                'title' => 'What’s something from your childhood that’s made a comeback?',
                'description' => 'From Tamagotchis to flared jeans, trends always circle back. What have you seen lately that gave you déjà vu?',
                'share_count' => 14,
            ],
            [
                'topic_id' => 12,
                'author_id' => 12,
                'title' => 'Vinland Saga: A lesson in maturity through vengeance?',
                'description' => 'Season 2 took a sharp turn toward introspection. Do you think it worked, or did you prefer the action-heavy start?',
                'share_count' => 33,
            ],
            [
                'topic_id' => 13,
                'author_id' => 13,
                'title' => 'Your favorite home remedies that actually work?',
                'description' => 'Old wives’ tales or not — some of these hacks just *work*. Share the ones that have stood the test of time.',
                'share_count' => 19,
            ],
            [
                'topic_id' => 14,
                'author_id' => 14,
                'title' => 'Ranking the best mecha anime of all time — who wins and why?',
                'description' => 'I’m compiling a list for my blog. Give me your top 3 mecha anime and your reasons. Let the debate begin!',
                'share_count' => 37,
            ],
            [
                'topic_id' => 15,
                'author_id' => 15,
                'title' => 'Why are so many people turning to minimalist lifestyles?',
                'description' => 'Is it burnout, clutter fatigue, or just a trend? Share your experience if you’ve tried minimalism.',
                'share_count' => 22,
            ],
            [
                'topic_id' => 16,
                'author_id' => 16,
                'title' => 'How can history education be made more engaging in schools?',
                'description' => 'Memorizing dates isn’t cutting it. What are some creative ways to get students emotionally invested in history?',
                'share_count' => 20,
            ],
            [
                'topic_id' => 17,
                'author_id' => 17,
                'title' => 'Hunter x Hunter’s Chimera Ant arc: Overrated or perfect?',
                'description' => 'It’s widely debated as either a masterpiece or bloated. Where do you stand?',
                'share_count' => 34,
            ],
            [
                'topic_id' => 18,
                'author_id' => 18,
                'title' => 'How do you define emotional intelligence in friendships?',
                'description' => 'Is it about listening, giving advice, or setting boundaries? Let’s talk about what makes someone emotionally “smart.”',
                'share_count' => 15,
            ],
            [
                'topic_id' => 19,
                'author_id' => 19,
                'title' => 'Most iconic anime openings of all time?',
                'description' => 'Let’s build a community playlist! Post your top picks and why they hit you right in the feels.',
                'share_count' => 41,
            ],
            [
                'topic_id' => 20,
                'author_id' => 20,
                'title' => 'The role of protest art in modern movements',
                'description' => 'From graffiti to digital illustrations, how has art helped push social change? Share some powerful examples.',
                'share_count' => 17,
            ],
            [
                'topic_id' => 21,
                'author_id' => 21,
                'title' => 'What series pulled off a perfect final episode?',
                'description' => 'Finales are tough to nail. Which shows actually stuck the landing in your opinion?',
                'share_count' => 28,
            ],
            [
                'topic_id' => 22,
                'author_id' => 22,
                'title' => 'What’s your experience with meditation or mindfulness?',
                'description' => 'Have you tried any apps, silent retreats, or breathwork that worked for you? Curious what’s out there.',
                'share_count' => 23,
            ],
            [
                'topic_id' => 23,
                'author_id' => 23,
                'title' => 'Chainsaw Man: Shock value or genius storytelling?',
                'description' => 'It’s wild, unhinged, and stylish — but does it actually *say* something? Let’s discuss.',
                'share_count' => 39,
            ],
            [
                'topic_id' => 24,
                'author_id' => 24,
                'title' => 'What keeps you from burning out in a creative field?',
                'description' => 'When your passion becomes your job, how do you avoid running dry?',
                'share_count' => 18,
            ],
            [
                'topic_id' => 25,
                'author_id' => 25,
                'title' => 'The best examples of “found family” in fiction?',
                'description' => 'There’s something beautiful about characters choosing each other. Which stories nailed this trope best?',
                'share_count' => 25,
            ],
            [
                'topic_id' => 26,
                'author_id' => 26,
                'title' => 'Why is GTO still relevant today?',
                'description' => 'Great Teacher Onizuka might be old, but its themes still hit hard. What makes it timeless to you?',
                'share_count' => 20,
            ],
            [
                'topic_id' => 27,
                'author_id' => 27,
                'title' => 'What makes a fictional world “immersive” to you?',
                'description' => 'Is it the lore, the maps, the music? Share your favorite immersive worlds and why they sucked you in.',
                'share_count' => 33,
            ],
            [
                'topic_id' => 28,
                'author_id' => 28,
                'title' => 'Should AI be taught in schools — and how early?',
                'description' => 'We’re heading into an AI-centric future. When’s the right age to start introducing these tools to students?',
                'share_count' => 24,
            ],
            [
                'topic_id' => 29,
                'author_id' => 29,
                'title' => 'Do introverts thrive more in online communities?',
                'description' => 'Some say the digital space gives quieter voices a chance to shine. What’s your experience?',
                'share_count' => 27,
            ],
            [
                'topic_id' => 30,
                'author_id' => 30,
                'title' => 'What are your go-to drawing exercises for improvement?',
                'description' => 'Trying to build a daily sketching habit. Looking for warm-ups or drills that actually level you up.',
                'share_count' => 30,
            ],
            [
                'topic_id' => 31,
                'author_id' => 31,
                'title' => 'What makes slice-of-life anime so comforting?',
                'description' => 'It’s low-stakes and heartwarming, but there’s clearly something deeper going on. Let’s talk comfort shows.',
                'share_count' => 22,
            ],
            [
                'topic_id' => 32,
                'author_id' => 32,
                'title' => 'What’s your “comfort book” and why?',
                'description' => 'The one you go back to when life feels chaotic. Could be childhood nostalgia or a timeless message.',
                'share_count' => 19,
            ],
            [
                'topic_id' => 33,
                'author_id' => 33,
                'title' => 'If you could redesign social media, what would change?',
                'description' => 'Less rage-bait? More depth? Better filters? Imagine building the ideal online community.',
                'share_count' => 27,
            ],
            [
                'topic_id' => 34,
                'author_id' => 34,
                'title' => 'What’s the best soundtrack in a video game?',
                'description' => 'From emotional piano themes to pulse-pounding battle music — which game’s OST stuck with you the longest?',
                'share_count' => 36,
            ],
            [
                'topic_id' => 35,
                'author_id' => 35,
                'title' => 'Do you think fandom culture is more positive or toxic today?',
                'description' => 'With passionate fans come passionate fights. Has it become too polarized — or is that just the internet?',
                'share_count' => 31,
            ],
            [
                'topic_id' => 36,
                'author_id' => 36,
                'title' => 'Anime that made you cry — but in a *good* way',
                'description' => 'We’ve all had that “I wasn’t ready for these emotions” moment. What anime hit you the hardest?',
                'share_count' => 29,
            ],
            [
                'topic_id' => 37,
                'author_id' => 37,
                'title' => 'Best ways to practice art without burning out?',
                'description' => 'I’m trying to improve but also not hate drawing. Tips for keeping the joy alive while pushing skills?',
                'share_count' => 21,
            ],
            [
                'topic_id' => 38,
                'author_id' => 38,
                'title' => 'What is a topic you wish more people cared about?',
                'description' => 'Could be environmental, cultural, ethical… What do you feel is ignored but deeply important?',
                'share_count' => 24,
            ],
            [
                'topic_id' => 39,
                'author_id' => 39,
                'title' => 'Which anime character’s growth arc felt the most real?',
                'description' => 'Some characters go through genuine change. Who had the most satisfying development?',
                'share_count' => 32,
            ],
            [
                'topic_id' => 40,
                'author_id' => 40,
                'title' => 'What’s a game that changed how you see the world?',
                'description' => 'Not just fun — something that challenged your worldview, even philosophically. Let’s hear your picks.',
                'share_count' => 28,
            ],
            [
                'topic_id' => 41,
                'author_id' => 41,
                'title' => 'What’s the most underrated manga you’ve read?',
                'description' => 'Hidden gems that deserve more love — drop titles that blew you away but never hit the mainstream.',
                'share_count' => 19,
            ],
            [
                'topic_id' => 42,
                'author_id' => 42,
                'title' => 'Are online courses worth the time?',
                'description' => 'Platforms like Coursera and Skillshare are booming. Have they actually helped you grow — or meh?',
                'share_count' => 25,
            ],
            [
                'topic_id' => 43,
                'author_id' => 43,
                'title' => 'What makes a community space feel welcoming to you?',
                'description' => 'Both online and in-person — what signals make you feel safe, included, and heard?',
                'share_count' => 23,
            ],
            [
                'topic_id' => 44,
                'author_id' => 44,
                'title' => 'Most “rewatchable” anime of all time?',
                'description' => 'Some shows never get old. What anime do you always find yourself rewatching — and why?',
                'share_count' => 34,
            ],
            [
                'topic_id' => 45,
                'author_id' => 45,
                'title' => 'How do you handle creative blocks?',
                'description' => 'We’ve all been stuck. What’s your go-to strategy to break through a dry spell in writing, art, or music?',
                'share_count' => 26,
            ],
            [
                'topic_id' => 46,
                'author_id' => 46,
                'title' => 'What piece of media changed the way you think?',
                'description' => 'Could be a book, film, series, or podcast — something that shifted your perspective for good.',
                'share_count' => 30,
            ],
            [
                'topic_id' => 47,
                'author_id' => User::all()->random()->id,
                'title' => 'What Are the Key Issues in This Election Season?',
                'description' => 'Let\'s discuss the most pressing matters influencing voters right now.',
                'share_count' => rand(5, 100),
            ],
            [
                'topic_id' => 48,
                'author_id' => User::all()->random()->id,
                'title' => 'How to Identify Fake News in 2025?',
                'description' => 'Tips and tools for navigating biased or misleading information.',
                'share_count' => rand(5, 100),
            ],
            [
                'topic_id' => 49,
                'author_id' => User::all()->random()->id,
                'title' => 'Latest Developments in Global Conflict Zones',
                'description' => 'Post your updates or insights about conflict regions around the world.',
                'share_count' => rand(5, 100),
            ],
            [
                'topic_id' => 50,
                'author_id' => User::all()->random()->id,
                'title' => 'Economic Impacts of Trade Wars',
                'description' => 'How are international policies affecting our economy?',
                'share_count' => rand(5, 100),
            ],
            [
                'topic_id' => 51,
                'author_id' => User::all()->random()->id,
                'title' => 'Understanding Modern Human Rights Movements',
                'description' => 'A place to explore ongoing campaigns and legal reforms.',
                'share_count' => rand(5, 100),
            ],
            [
                'topic_id' => 1,
                'author_id' => User::all()->random()->id,
                'title' => 'What is history really for?',
                'description' => 'Is it to learn or just remember?',
                'share_count' => rand(0, 30),
            ],
            [
                'topic_id' => 2,
                'author_id' => User::all()->random()->id,
                'title' => 'Why is Frieren so relatable?',
                'description' => 'Even though she’s immortal, she feels real.',
                'share_count' => rand(0, 30),
            ],
            [
                'topic_id' => 3,
                'author_id' => User::all()->random()->id,
                'title' => 'When do you cook during college?',
                'description' => 'Morning, night, or just weekend bulk meals?',
                'share_count' => rand(0, 30),
            ],
            [
                'topic_id' => 4,
                'author_id' => User::all()->random()->id,
                'title' => 'Where can I watch old Ultraman episodes?',
                'description' => 'Streaming or DVD? I need that nostalgia!',
                'share_count' => rand(0, 30),
            ],
            [
                'topic_id' => 5,
                'author_id' => User::all()->random()->id,
                'title' => 'How did you learn Laravel fast?',
                'description' => 'Tips for a beginner trying to build fast.',
                'share_count' => rand(0, 30),
            ],
            [
                'topic_id' => 6,
                'author_id' => User::all()->random()->id,
                'title' => 'What’s your daily declutter habit?',
                'description' => 'I’m starting with 5 minutes a day.',
                'share_count' => rand(0, 30),
            ],
            [
                'topic_id' => 7,
                'author_id' => User::all()->random()->id,
                'title' => 'Why does a morning walk help so much?',
                'description' => 'Clear mind, better mood, every time.',
                'share_count' => rand(0, 30),
            ],
            [
                'topic_id' => 8,
                'author_id' => User::all()->random()->id,
                'title' => 'When is long-distance worth it?',
                'description' => 'Let’s be honest: does it work?',
                'share_count' => rand(0, 30),
            ],
            [
                'topic_id' => 9,
                'author_id' => User::all()->random()->id,
                'title' => 'Where do you plan your week?',
                'description' => 'Notion, Google Calendar, or paper?',
                'share_count' => rand(0, 30),
            ],
            [
                'topic_id' => 10,
                'author_id' => User::all()->random()->id,
                'title' => 'How do I decorate on a budget?',
                'description' => 'Room still feels empty as a student.',
                'share_count' => rand(0, 30),
            ],
            [
                'topic_id' => 11,
                'author_id' => User::all()->random()->id,
                'title' => 'What makes fashion “cool” to you?',
                'description' => 'Brand? Fit? Personality?',
                'share_count' => rand(0, 30),
            ],
            [
                'topic_id' => 12,
                'author_id' => User::all()->random()->id,
                'title' => 'Why do we skip self-care when stressed?',
                'description' => 'Shouldn’t it be the opposite?',
                'share_count' => rand(0, 30),
            ],
            [
                'topic_id' => 13,
                'author_id' => User::all()->random()->id,
                'title' => 'When are you most productive?',
                'description' => 'Late night, early morning, or mid-day burst?',
                'share_count' => rand(0, 30),
            ],
            [
                'topic_id' => 14,
                'author_id' => User::all()->random()->id,
                'title' => 'Where did The Last Jedi go wrong?',
                'description' => 'Plot, characters, tone, or just timing?',
                'share_count' => rand(0, 30),
            ],
            [
                'topic_id' => 15,
                'author_id' => User::all()->random()->id,
                'title' => 'How will Secret Wars change the MCU?',
                'description' => 'Multiverse reset? Final chapter?',
                'share_count' => rand(0, 30),
            ],
            [
                'topic_id' => 16,
                'author_id' => User::all()->random()->id,
                'title' => 'What’s your fav Stranger Things moment?',
                'description' => 'I can’t pick between season 1 and 4.',
                'share_count' => rand(0, 30),
            ],
            [
                'topic_id' => 17,
                'author_id' => User::all()->random()->id,
                'title' => 'Why is Dwight so iconic?',
                'description' => 'Is it the quotes or the chaos?',
                'share_count' => rand(0, 30),
            ],
            [
                'topic_id' => 18,
                'author_id' => User::all()->random()->id,
                'title' => 'When did Walt truly break bad?',
                'description' => 'What was the turning point for you?',
                'share_count' => rand(0, 30),
            ],
            [
                'topic_id' => 19,
                'author_id' => User::all()->random()->id,
                'title' => 'Where would a Thrones sequel even start?',
                'description' => 'Arya’s journey? Rebuilding Westeros?',
                'share_count' => rand(0, 30),
            ],
            [
                'topic_id' => 20,
                'author_id' => User::all()->random()->id,
                'title' => 'How strong is Sam’s loyalty?',
                'description' => 'Would you have made it that far for Frodo?',
                'share_count' => rand(0, 30),
            ],
            [
                'author_id' => User::all()->random()->id,
                'topic_id' => 21,
                'title' => 'Who’s your favorite K-Pop group right now?',
                'description' => 'I’m torn between NewJeans and Aespa. Their latest comebacks have been amazing!',
                'share_count' => rand(0, 30),
            ],
            [
                'author_id' => User::all()->random()->id,
                'topic_id' => 22,
                'title' => 'What’s trending this week?',
                'description' => 'Let’s gather the most viral moments and memes from this week!',
                'share_count' => rand(0, 30),
            ],
            [
                'author_id' => User::all()->random()->id,
                'topic_id' => 23,
                'title' => 'Oscar snubs that still bother you',
                'description' => 'What actor or movie deserved an Oscar but didn’t win?',
                'share_count' => rand(0, 30),
            ],
            [
                'author_id' => User::all()->random()->id,
                'topic_id' => 24,
                'title' => 'Saddest moment in Naruto?',
                'description' => 'Mine was Jiraiya’s death. What about yours?',
                'share_count' => rand(0, 30),
            ],
            [
                'author_id' => User::all()->random()->id,
                'topic_id' => 25,
                'title' => 'One Piece live-action thoughts?',
                'description' => 'What did you think of the casting and the tone?',
                'share_count' => rand(0, 30),
            ],
            [
                'author_id' => User::all()->random()->id,
                'topic_id' => 26,
                'title' => 'Eren: Hero or Villain?',
                'description' => 'The final arc left a lot to unpack.',
                'share_count' => rand(0, 30),
            ],
            [
                'author_id' => User::all()->random()->id,
                'topic_id' => 27,
                'title' => 'Funniest Spongebob quote?',
                'description' => '“I’m ugly and I’m proud.” gets me every time.',
                'share_count' => rand(0, 30),
            ],
            [
                'author_id' => User::all()->random()->id,
                'topic_id' => 28,
                'title' => 'Zuko’s character development is elite',
                'description' => 'Anyone else tear up during his apology to Uncle Iroh?',
                'share_count' => rand(0, 30),
            ],
            [
                'author_id' => User::all()->random()->id,
                'topic_id' => 29,
                'title' => 'Best Hashira fight?',
                'description' => 'Personally, Rengoku vs Akaza takes the cake.',
                'share_count' => rand(0, 30),
            ],
            [
                'author_id' => User::all()->random()->id,
                'topic_id' => 30,
                'title' => 'Adventure Time episodes that hit deep',
                'description' => 'This show went from silly to philosophical real fast.',
                'share_count' => rand(0, 30),
            ],
            [
                'author_id' => User::all()->random()->id,
                'topic_id' => 31,
                'title' => 'BoJack Horseman and mental health',
                'description' => 'This show really portrayed depression in a real and raw way.',
                'share_count' => rand(0, 30),
            ],
            [
                'author_id' => User::all()->random()->id,
                'topic_id' => 32,
                'title' => 'Favorite Studio Ghibli movie?',
                'description' => 'For me, it’s *Spirited Away*. What about you?',
                'share_count' => rand(0, 30),
            ],
            [
                'author_id' => User::all()->random()->id,
                'topic_id' => 33,
                'title' => 'Best indie animated film you’ve seen?',
                'description' => 'Loving “Wolfwalkers” and “Song of the Sea” recently.',
                'share_count' => rand(0, 30),
            ],
            [
                'author_id' => User::all()->random()->id,
                'topic_id' => 34,
                'title' => 'How do rockets escape Earth’s gravity?',
                'description' => 'Let’s discuss thrust, velocity, and escape trajectories.',
                'share_count' => rand(0, 30),
            ],
            [
                'author_id' => User::all()->random()->id,
                'topic_id' => 35,
                'title' => 'What is polymorphism in OOP?',
                'description' => 'Explain like I’m five!',
                'share_count' => rand(0, 30),
            ],
            [
                'author_id' => User::all()->random()->id,
                'topic_id' => 36,
                'title' => 'Favorite medieval castle and why?',
                'description' => 'I’m fascinated by Neuschwanstein Castle. What about you?',
                'share_count' => rand(0, 30),
            ],
            [
                'author_id' => User::all()->random()->id,
                'topic_id' => 37,
                'title' => 'Coolest fossil you’ve ever seen?',
                'description' => 'I saw a full Triceratops skull at a museum once!',
                'share_count' => rand(0, 30),
            ],
            [
                'author_id' => User::all()->random()->id,
                'topic_id' => 38,
                'title' => 'Quantum superposition explained simply?',
                'description' => 'Can anyone explain this without invoking Schrödinger’s cat?',
                'share_count' => rand(0, 30),
            ],
            [
                'author_id' => User::all()->random()->id,
                'topic_id' => 39,
                'title' => 'Best documentaries on climate change?',
                'description' => '*Before the Flood* and *Our Planet* are my top picks.',
                'share_count' => rand(0, 30),
            ],
            [
                'author_id' => User::all()->random()->id,
                'topic_id' => 40,
                'title' => 'Which philosopher influenced you the most?',
                'description' => 'Stoicism has been life-changing for me.',
                'share_count' => rand(0, 30),
            ],
            [
                'author_id' => User::all()->random()->id,
                'topic_id' => 41,
                'title' => 'Most peaceful world religion?',
                'description' => 'Let’s share insights from various faiths.',
                'share_count' => rand(0, 30),
            ],
            [
                'author_id' => User::all()->random()->id,
                'topic_id' => 42,
                'title' => 'Best way to learn a new language?',
                'description' => 'Immersion or apps like Duolingo? What worked for you?',
                'share_count' => rand(0, 30),
            ],
            [
                'author_id' => User::all()->random()->id,
                'topic_id' => 43,
                'title' => 'College tip that saved your semester?',
                'description' => 'Mine was discovering Pomodoro and Notion!',
                'share_count' => rand(0, 30),
            ],
            [
                'author_id' => User::all()->random()->id,
                'topic_id' => 44,
                'title' => 'Most pressing issue in global news?',
                'description' => 'Let’s keep it respectful and insightful.',
                'share_count' => rand(0, 30),
            ],
            [
                'author_id' => User::all()->random()->id,
                'topic_id' => 45,
                'title' => 'What’s a local issue you care about?',
                'description' => 'Let’s raise awareness and discuss solutions.',
                'share_count' => rand(0, 30),
            ],
            [
                'author_id' => User::all()->random()->id,
                'topic_id' => 46,
                'title' => 'Law or policy that needs changing?',
                'description' => 'Mine is around housing and zoning reform.',
                'share_count' => rand(0, 30),
            ],
            [
                'author_id' => User::all()->random()->id,
                'topic_id' => 47,
                'title' => 'Which election are you closely watching?',
                'description' => 'Let’s analyze the platforms and candidates.',
                'share_count' => rand(0, 30),
            ],
            [
                'author_id' => User::all()->random()->id,
                'topic_id' => 48,
                'title' => 'How do you verify news online?',
                'description' => 'Share your fact-checking methods and tools.',
                'share_count' => rand(0, 30),
            ],
            [
                'author_id' => User::all()->random()->id,
                'topic_id' => 49,
                'title' => 'What’s happening in [conflict region] right now?',
                'description' => 'Let’s keep it informative and sensitive.',
                'share_count' => rand(0, 30),
            ],
            [
                'author_id' => User::all()->random()->id,
                'topic_id' => 50,
                'title' => 'How does inflation affect politics?',
                'description' => 'Interesting to see how governments respond.',
                'share_count' => rand(0, 30),
            ],
            [
                'author_id' => User::all()->random()->id,
                'topic_id' => 51,
                'title' => 'Which human rights issue needs more spotlight?',
                'description' => 'Let’s bring awareness to global causes.',
                'share_count' => rand(0, 30),
            ],
        ], uniqueBy: 'id');

    }
}
