<?php

namespace Database\Seeders;

use App\Models\Topic;
use App\Models\User;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class TopicSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Topic::upsert([
            [
                'owner_id' => User::all()->random()['id'],
                'name' => 'medieval',
                'genre_id' => 1,
                'description' => 'Discussing medieval related topics.',
                'icon_image_link' => 'images/topic_icons/topic_1_icon.png',
                'banner_image_link' => 'images/topic_banners/topic_1_banner.png',
            ],
            [
                'owner_id' => User::all()->random()['id'],
                'name' => 'frieren',
                'genre_id' => 3,
                'description' => 'Talking about Frieren related topics here.',
                'icon_image_link' => 'images/topic_icons/topic_2_icon.png',
                'banner_image_link' => 'images/topic_banners/topic_2_banner.png',
            ],
            [
                'owner_id' => User::all()->random()['id'],
                'name' => 'cooking',
                'genre_id' => 2,
                'description' => 'The channel for beginners, advanced cooking related topics.',
                'icon_image_link' => 'images/topic_icons/topic_3_icon.png',
                'banner_image_link' => 'images/topic_banners/topic_3_banner.png',
            ],
            [
                'owner_id' => User::all()->random()['id'],
                'name' => 'ultramen',
                'genre_id' => 3,
                'description' => 'Ultramen classic.',
                'icon_image_link' => 'images/topic_icons/topic_4_icon.png',
                'banner_image_link' => 'images/topic_banners/topic_4_banner.png',
            ],
            [
                'owner_id' => User::all()->random()['id'],
                'name' => 'programming',
                'genre_id' => 1,
                'description' => 'Discuss coding related topics here.',
                'icon_image_link' => 'images/topic_icons/topic_5_icon.png',
                'banner_image_link' => 'images/topic_banners/topic_5_banner.png',
            ],
            [
                'owner_id' => User::all()->random()['id'],
                'name' => 'minimalist_living',
                'genre_id' => 1,
                'description' => 'Exploring simplicity in life and living spaces.',
                'icon_image_link' => 'images/topic_icons/topic_6_icon.png',
                'banner_image_link' => 'images/topic_banners/topic_6_banner.png',
            ],
            [
                'owner_id' => User::all()->random()['id'],
                'name' => 'healthy_habits',
                'genre_id' => 1,
                'description' => 'Discussing routines and practices for better health.',
                'icon_image_link' => 'images/topic_icons/topic_7_icon.png',
                'banner_image_link' => 'images/topic_banners/topic_7_banner.png',
            ],
            [
                'owner_id' => User::all()->random()['id'],
                'name' => 'relationship_advice',
                'genre_id' => 1,
                'description' => 'Sharing experiences and tips for relationships.',
                'icon_image_link' => 'images/topic_icons/topic_8_icon.png',
                'banner_image_link' => 'images/topic_banners/topic_8_banner.png',
            ],
            [
                'owner_id' => User::all()->random()['id'],
                'name' => 'time_management',
                'genre_id' => 1,
                'description' => 'Tips and strategies for effective time use.',
                'icon_image_link' => 'images/topic_icons/topic_9_icon.png',
                'banner_image_link' => 'images/topic_banners/topic_9_banner.png',
            ],
            [
                'owner_id' => User::all()->random()['id'],
                'name' => 'interior_design',
                'genre_id' => 1,
                'description' => 'Aesthetic and functional home ideas.',
                'icon_image_link' => 'images/topic_icons/topic_10_icon.png',
                'banner_image_link' => 'images/topic_banners/topic_10_banner.png',
            ],
            [
                'owner_id' => User::all()->random()['id'],
                'name' => 'fashion_trends',
                'genre_id' => 1,
                'description' => 'Discussing the latest in style and clothing.',
                'icon_image_link' => 'images/topic_icons/topic_11_icon.png',
                'banner_image_link' => 'images/topic_banners/topic_11_banner.png',
            ],
            [
                'owner_id' => User::all()->random()['id'],
                'name' => 'self-care_routines',
                'genre_id' => 1,
                'description' => 'Mental and physical self-care practices.',
                'icon_image_link' => 'images/topic_icons/topic_12_icon.png',
                'banner_image_link' => 'images/topic_banners/topic_12_banner.png',
            ],
            [
                'owner_id' => User::all()->random()['id'],
                'name' => 'productivity_hacks',
                'genre_id' => 1,
                'description' => 'Boosting efficiency in daily tasks.',
                'icon_image_link' => 'images/topic_icons/topic_13_icon.png',
                'banner_image_link' => 'images/topic_banners/topic_13_banner.png',
            ],
            [
                'owner_id' => User::all()->random()['id'],
                'name' => 'star_wars',
                'genre_id' => 2,
                'description' => 'Discussing everything Star Wars.',
                'icon_image_link' => 'images/topic_icons/topic_14_icon.png',
                'banner_image_link' => 'images/topic_banners/topic_14_banner.png',
            ],
            [
                'owner_id' => User::all()->random()['id'],
                'name' => 'marvel_cinematic_universe',
                'genre_id' => 2,
                'description' => 'From Iron Man to Avengers, it’s all here.',
                'icon_image_link' => 'images/topic_icons/topic_15_icon.png',
                'banner_image_link' => 'images/topic_banners/topic_15_banner.png',
            ],
            [
                'owner_id' => User::all()->random()['id'],
                'name' => 'stranger_things',
                'genre_id' => 2,
                'description' => 'Fan theories and episode discussions.',
                'icon_image_link' => 'images/topic_icons/topic_16_icon.png',
                'banner_image_link' => 'images/topic_banners/topic_16_banner.png',
            ],
            [
                'owner_id' => User::all()->random()['id'],
                'name' => 'the_office',
                'genre_id' => 2,
                'description' => 'Classic sitcom discussions and memes.',
                'icon_image_link' => 'images/topic_icons/topic_17_icon.png',
                'banner_image_link' => 'images/topic_banners/topic_17_banner.png',
            ],
            [
                'owner_id' => User::all()->random()['id'],
                'name' => 'breaking_bad',
                'genre_id' => 2,
                'description' => 'Dive deep into the story and characters.',
                'icon_image_link' => 'images/topic_icons/topic_18_icon.png',
                'banner_image_link' => 'images/topic_banners/topic_18_banner.png',
            ],
            [
                'owner_id' => User::all()->random()['id'],
                'name' => 'game_of_thrones',
                'genre_id' => 2,
                'description' => 'House wars and lore from Westeros.',
                'icon_image_link' => 'images/topic_icons/topic_19_icon.png',
                'banner_image_link' => 'images/topic_banners/topic_19_banner.png',
            ],
            [
                'owner_id' => User::all()->random()['id'],
                'name' => 'lord_of_the_rings',
                'genre_id' => 2,
                'description' => 'Middle-earth discussion hub.',
                'icon_image_link' => 'images/topic_icons/topic_20_icon.png',
                'banner_image_link' => 'images/topic_banners/topic_20_banner.png',
            ],
            [
                'owner_id' => User::all()->random()['id'],
                'name' => 'k-pop_central',
                'genre_id' => 2,
                'description' => 'Talk about idols, music, and fandoms.',
                'icon_image_link' => 'images/topic_icons/topic_21_icon.png',
                'banner_image_link' => 'images/topic_banners/topic_21_banner.png',
            ],

            [
                'owner_id' => User::all()->random()['id'],
                'name' => 'pop_culture_watch',
                'genre_id' => 2,
                'description' => 'Tracking trends and viral phenomena.',
                'icon_image_link' => 'images/topic_icons/topic_22_icon.png',
                'banner_image_link' => 'images/topic_banners/topic_22_banner.png',
            ],
            [
                'owner_id' => User::all()->random()['id'],
                'name' => 'award_show_discussions',
                'genre_id' => 2,
                'description' => 'Oscars, Grammys and more.',
                'icon_image_link' => 'images/topic_icons/topic_23_icon.png',
                'banner_image_link' => 'images/topic_banners/topic_23_banner.png',
            ],
            [
                'owner_id' => User::all()->random()['id'],
                'name' => 'naruto',
                'genre_id' => 3,
                'description' => 'From Konoha to the Akatsuki. Everything Naruto.',
                'icon_image_link' => 'images/topic_icons/topic_24_icon.png',
                'banner_image_link' => 'images/topic_banners/topic_24_banner.png',
            ],
            [
                'owner_id' => User::all()->random()['id'],
                'name' => 'one_piece',
                'genre_id' => 3,
                'description' => 'Sailing with Luffy and the Straw Hats.',
                'icon_image_link' => 'images/topic_icons/topic_25_icon.png',
                'banner_image_link' => 'images/topic_banners/topic_25_banner.png',
            ],
            [
                'owner_id' => User::all()->random()['id'],
                'name' => 'attack_on_titan',
                'genre_id' => 3,
                'description' => 'Titans, Marley, and beyond.',
                'icon_image_link' => 'images/topic_icons/topic_26_icon.png',
                'banner_image_link' => 'images/topic_banners/topic_26_banner.png',
            ],
            [
                'owner_id' => User::all()->random()['id'],
                'name' => 'spongebob_squarepants',
                'genre_id' => 3,
                'description' => 'Underwater laughs and quotes.',
                'icon_image_link' => 'images/topic_icons/topic_27_icon.png',
                'banner_image_link' => 'images/topic_banners/topic_27_banner.png',
            ],
            [
                'owner_id' => User::all()->random()['id'],
                'name' => 'avatar:_the_last_airbender',
                'genre_id' => 3,
                'description' => 'Bending elements and deep lore.',
                'icon_image_link' => 'images/topic_icons/topic_28_icon.png',
                'banner_image_link' => 'images/topic_banners/topic_28_banner.png',
            ],
            [
                'owner_id' => User::all()->random()['id'],
                'name' => 'demon_slayer',
                'genre_id' => 3,
                'description' => 'Demon hunting and breathing styles.',
                'icon_image_link' => 'images/topic_icons/topic_29_icon.png',
                'banner_image_link' => 'images/topic_banners/topic_29_banner.png',
            ],
            [
                'owner_id' => User::all()->random()['id'],
                'name' => 'adventure_time',
                'genre_id' => 3,
                'description' => 'Ooo, Finn, and the Land beyond.',
                'icon_image_link' => 'images/topic_icons/topic_30_icon.png',
                'banner_image_link' => 'images/topic_banners/topic_30_banner.png',
            ],
            [
                'owner_id' => User::all()->random()['id'],
                'name' => 'bojack_horseman',
                'genre_id' => 3,
                'description' => 'Hollywood satire and personal struggles.',
                'icon_image_link' => 'images/topic_icons/topic_31_icon.png',
                'banner_image_link' => 'images/topic_banners/topic_31_banner.png',
            ],
            [
                'owner_id' => User::all()->random()['id'],
                'name' => 'studio_ghibli_talk',
                'genre_id' => 3,
                'description' => 'Exploring the worlds of Miyazaki.',
                'icon_image_link' => 'images/topic_icons/topic_32_icon.png',
                'banner_image_link' => 'images/topic_banners/topic_32_banner.png',
            ],
            [
                'owner_id' => User::all()->random()['id'],
                'name' => 'indie_animation',
                'genre_id' => 3,
                'description' => 'Celebrating non-mainstream gems.',
                'icon_image_link' => 'images/topic_icons/topic_33_icon.png',
                'banner_image_link' => 'images/topic_banners/topic_33_banner.png',
            ],
            [
                'owner_id' => User::all()->random()['id'],
                'name' => 'rocket_science',
                'genre_id' => 4,
                'description' => 'Orbit mechanics to propulsion.',
                'icon_image_link' => 'images/topic_icons/topic_34_icon.png',
                'banner_image_link' => 'images/topic_banners/topic_34_banner.png',
            ],
            [
                'owner_id' => User::all()->random()['id'],
                'name' => 'programming_concepts',
                'genre_id' => 4,
                'description' => 'Discussing programming principles.',
                'icon_image_link' => 'images/topic_icons/topic_35_icon.png',
                'banner_image_link' => 'images/topic_banners/topic_35_banner.png',
            ],
            [
                'owner_id' => User::all()->random()['id'],
                'name' => 'medieval_history',
                'genre_id' => 4,
                'description' => 'Castles, knights, and crusades.',
                'icon_image_link' => 'images/topic_icons/topic_36_icon.png',
                'banner_image_link' => 'images/topic_banners/topic_36_banner.png',
            ],
            [
                'owner_id' => User::all()->random()['id'],
                'name' => 'paleontology',
                'genre_id' => 4,
                'description' => 'Dinosaurs, fossils, and ancient life.',
                'icon_image_link' => 'images/topic_icons/topic_37_icon.png',
                'banner_image_link' => 'images/topic_banners/topic_37_banner.png',
            ],
            [
                'owner_id' => User::all()->random()['id'],
                'name' => 'quantum_physics',
                'genre_id' => 4,
                'description' => 'The weird world of particles.',
                'icon_image_link' => 'images/topic_icons/topic_38_icon.png',
                'banner_image_link' => 'images/topic_banners/topic_38_banner.png',
            ],
            [
                'owner_id' => User::all()->random()['id'],
                'name' => 'environmental_science',
                'genre_id' => 4,
                'description' => 'Climate change and ecosystems.',
                'icon_image_link' => 'images/topic_icons/topic_39_icon.png',
                'banner_image_link' => 'images/topic_banners/topic_39_banner.png',
            ],
            [
                'owner_id' => User::all()->random()['id'],
                'name' => 'philosophy_101',
                'genre_id' => 4,
                'description' => 'Debates, theories, and thought experiments.',
                'icon_image_link' => 'images/topic_icons/topic_40_icon.png',
                'banner_image_link' => 'images/topic_banners/topic_40_banner.png',
            ],
            [
                'owner_id' => User::all()->random()['id'],
                'name' => 'world_religions',
                'genre_id' => 4,
                'description' => 'Exploring beliefs and faiths.',
                'icon_image_link' => 'images/topic_icons/topic_41_icon.png',
                'banner_image_link' => 'images/topic_banners/topic_41_banner.png',
            ],
            [
                'owner_id' => User::all()->random()['id'],
                'name' => 'language_learning',
                'genre_id' => 4,
                'description' => 'Grammar tips, vocab, and immersion.',
                'icon_image_link' => 'images/topic_icons/topic_42_icon.png',
                'banner_image_link' => 'images/topic_banners/topic_42_banner.png',
            ],
            [
                'owner_id' => User::all()->random()['id'],
                'name' => 'college_survival_guide',
                'genre_id' => 4,
                'description' => 'Study hacks and college life advice.',
                'icon_image_link' => 'images/topic_icons/topic_43_icon.png',
                'banner_image_link' => 'images/topic_banners/topic_43_banner.png',
            ],
            [
                'owner_id' => User::all()->random()['id'],
                'name' => 'global_headlines',
                'genre_id' => 5,
                'description' => 'Discussing current world news.',
                'icon_image_link' => 'images/topic_icons/topic_44_icon.png',
                'banner_image_link' => 'images/topic_banners/topic_44_banner.png',
            ],
            [
                'owner_id' => User::all()->random()['id'],
                'name' => 'local_issues',
                'genre_id' => 5,
                'description' => 'Community-level problems and insights.',
                'icon_image_link' => 'images/topic_icons/topic_45_icon.png',
                'banner_image_link' => 'images/topic_banners/topic_45_banner.png',
            ],
            [
                'owner_id' => User::all()->random()['id'],
                'name' => 'policy_and_law',
                'genre_id' => 5,
                'description' => 'Regulations, rights, and policy-making.',
                'icon_image_link' => 'images/topic_icons/topic_46_icon',
                'banner_image_link' => 'images/topic_banners/topic_46_banner.png',
            ],
            [
                'owner_id' => User::all()->random()['id'],
                'name' => 'election_watch',
                'genre_id' => 5,
                'description' => 'Covering election seasons globally.',
                'icon_image_link' => 'images/topic_icons/topic_47_icon.png',
                'banner_image_link' => 'images/topic_banners/topic_47_banner.png',
            ],
            [
                'owner_id' => User::all()->random()['id'],
                'name' => 'media_literacy',
                'genre_id' => 5,
                'description' => 'Spotting bias, fake news, and disinfo.',
                'icon_image_link' => 'images/topic_icons/topic_48_icon.png',
                'banner_image_link' => 'images/topic_banners/topic_48_banner.png',
            ],
            [
                'owner_id' => User::all()->random()['id'],
                'name' => 'conflict_zones',
                'genre_id' => 5,
                'description' => 'Understanding war and unrest areas.',
                'icon_image_link' => 'images/topic_icons/topic_49_icon',
                'banner_image_link' => 'images/topic_banners/topic_49_banner.png',
            ],
            [
                'owner_id' => User::all()->random()['id'],
                'name' => 'economic_politics',
                'genre_id' => 5,
                'description' => 'Money and policy intersections.',
                'icon_image_link' => 'images/topic_icons/topic_50_icon.png',
                'banner_image_link' => 'images/topic_banners/topic_50_banner.png',
            ],
            [
                'owner_id' => User::all()->random()['id'],
                'name' => 'human_rights_talk',
                'genre_id' => 5,
                'description' => 'Discussing justice and advocacy.',
                'icon_image_link' => 'images/topic_icons/topic_51_icon.png',
                'banner_image_link' => 'images/topic_banners/topic_51_banner.png',
            ],
        ], uniqueBy: 'id');
    }
}
