<?php

namespace Database\Seeders;

use App\Models\Topic;
use App\Models\User;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class TopicSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Topic::insert([
            [
                'owner_id' => User::all()->random()['id'],
                'name' => 'Medieval',
                'genre_id' => 1,
                'description' => 'Discussing medieval related topics.',
                'icon_image_link' => 'topic_1_icon',
                'banner_image_link' => 'topic_1_banner',
            ],
            [
                'owner_id' => User::all()->random()['id'],
                'name' => 'Frieren',
                'genre_id' => 3,
                'description' => 'Talking about Frieren related topics here.',
                'icon_image_link' => 'topic_2_icon',
                'banner_image_link' => 'topic_2_banner',
            ],
            [
                'owner_id' => User::all()->random()['id'],
                'name' => 'Cooking',
                'genre_id' => 2,
                'description' => 'The channel for beginners, advanced cooking related topics.',
                'icon_image_link' => 'topic_3_icon',
                'banner_image_link' => 'topic_3_banner',
            ],
            [
                'owner_id' => User::all()->random()['id'],
                'name' => 'Ultramen',
                'genre_id' => 3,
                'description' => 'Ultramen classic.',
                'icon_image_link' => 'topic_4_icon',
                'banner_image_link' => 'topic_4_banner',
            ],
            [
                'owner_id' => User::all()->random()['id'],
                'name' => 'Programming',
                'genre_id' => 1,
                'description' => 'Discuss coding related topics here.',
                'icon_image_link' => 'topic_5_icon',
                'banner_image_link' => 'topic_5_banner',
            ],
            [
                'owner_id' => User::all()->random()['id'],
                'name' => 'Minimalist Living',
                'genre_id' => 1,
                'description' => 'Exploring simplicity in life and living spaces.',
                'icon_image_link' => 'topic_1_icon',
                'banner_image_link' => 'topic_1_banner',
            ],
            [
                'owner_id' => User::all()->random()['id'],
                'name' => 'Healthy Habits',
                'genre_id' => 1,
                'description' => 'Discussing routines and practices for better health.',
                'icon_image_link' => 'topic_2_icon',
                'banner_image_link' => 'topic_2_banner',
            ],
            [
                'owner_id' => User::all()->random()['id'],
                'name' => 'Relationship Advice',
                'genre_id' => 1,
                'description' => 'Sharing experiences and tips for relationships.',
                'icon_image_link' => 'topic_3_icon',
                'banner_image_link' => 'topic_3_banner',
            ],
            [
                'owner_id' => User::all()->random()['id'],
                'name' => 'Time Management',
                'genre_id' => 1,
                'description' => 'Tips and strategies for effective time use.',
                'icon_image_link' => 'topic_4_icon',
                'banner_image_link' => 'topic_4_banner',
            ],
            [
                'owner_id' => User::all()->random()['id'],
                'name' => 'Interior Design',
                'genre_id' => 1,
                'description' => 'Aesthetic and functional home ideas.',
                'icon_image_link' => 'topic_5_icon',
                'banner_image_link' => 'topic_5_banner',
            ],
            [
                'owner_id' => User::all()->random()['id'],
                'name' => 'Fashion Trends',
                'genre_id' => 1,
                'description' => 'Discussing the latest in style and clothing.',
                'icon_image_link' => 'topic_6_icon',
                'banner_image_link' => 'topic_6_banner',
            ],
            [
                'owner_id' => User::all()->random()['id'],
                'name' => 'Self-Care Routines',
                'genre_id' => 1,
                'description' => 'Mental and physical self-care practices.',
                'icon_image_link' => 'topic_7_icon',
                'banner_image_link' => 'topic_7_banner',
            ],
            [
                'owner_id' => User::all()->random()['id'],
                'name' => 'Productivity Hacks',
                'genre_id' => 1,
                'description' => 'Boosting efficiency in daily tasks.',
                'icon_image_link' => 'topic_8_icon',
                'banner_image_link' => 'topic_8_banner',
            ],
            [
                'owner_id' => User::all()->random()['id'],
                'name' => 'Star Wars',
                'genre_id' => 2,
                'description' => 'Discussing everything Star Wars.',
                'icon_image_link' => 'topic_9_icon',
                'banner_image_link' => 'topic_9_banner',
            ],
            [
                'owner_id' => User::all()->random()['id'],
                'name' => 'Marvel Cinematic Universe',
                'genre_id' => 2,
                'description' => 'From Iron Man to Avengers, it’s all here.',
                'icon_image_link' => 'topic_10_icon',
                'banner_image_link' => 'topic_10_banner',
            ],
            [
                'owner_id' => User::all()->random()['id'],
                'name' => 'Stranger Things',
                'genre_id' => 2,
                'description' => 'Fan theories and episode discussions.',
                'icon_image_link' => 'topic_11_icon',
                'banner_image_link' => 'topic_11_banner',
            ],
            [
                'owner_id' => User::all()->random()['id'],
                'name' => 'The Office',
                'genre_id' => 2,
                'description' => 'Classic sitcom discussions and memes.',
                'icon_image_link' => 'topic_12_icon',
                'banner_image_link' => 'topic_12_banner',
            ],
            [
                'owner_id' => User::all()->random()['id'],
                'name' => 'Breaking Bad',
                'genre_id' => 2,
                'description' => 'Dive deep into the story and characters.',
                'icon_image_link' => 'topic_13_icon',
                'banner_image_link' => 'topic_13_banner',
            ],
            [
                'owner_id' => User::all()->random()['id'],
                'name' => 'Game of Thrones',
                'genre_id' => 2,
                'description' => 'House wars and lore from Westeros.',
                'icon_image_link' => 'topic_14_icon',
                'banner_image_link' => 'topic_14_banner',
            ],
            [
                'owner_id' => User::all()->random()['id'],
                'name' => 'Lord of the Rings',
                'genre_id' => 2,
                'description' => 'Middle-earth discussion hub.',
                'icon_image_link' => 'topic_15_icon',
                'banner_image_link' => 'topic_15_banner',
            ],
            [
                'owner_id' => User::all()->random()['id'],
                'name' => 'K-Pop Central',
                'genre_id' => 2,
                'description' => 'Talk about idols, music, and fandoms.',
                'icon_image_link' => 'topic_16_icon',
                'banner_image_link' => 'topic_16_banner',
            ],

            [
                'owner_id' => User::all()->random()['id'],
                'name' => 'Pop Culture Watch',
                'genre_id' => 2,
                'description' => 'Tracking trends and viral phenomena.',
                'icon_image_link' => 'topic_17_icon',
                'banner_image_link' => 'topic_17_banner',
            ],
            [
                'owner_id' => User::all()->random()['id'],
                'name' => 'Award Show Discussions',
                'genre_id' => 2,
                'description' => 'Oscars, Grammys and more.',
                'icon_image_link' => 'topic_18_icon',
                'banner_image_link' => 'topic_18_banner',
            ],
            [
                'owner_id' => User::all()->random()['id'],
                'name' => 'Naruto',
                'genre_id' => 3,
                'description' => 'From Konoha to the Akatsuki. Everything Naruto.',
                'icon_image_link' => 'topic_19_icon',
                'banner_image_link' => 'topic_19_banner',
            ],
            [
                'owner_id' => User::all()->random()['id'],
                'name' => 'One Piece',
                'genre_id' => 3,
                'description' => 'Sailing with Luffy and the Straw Hats.',
                'icon_image_link' => 'topic_20_icon',
                'banner_image_link' => 'topic_20_banner',
            ],
            [
                'owner_id' => User::all()->random()['id'],
                'name' => 'Attack on Titan',
                'genre_id' => 3,
                'description' => 'Titans, Marley, and beyond.',
                'icon_image_link' => 'topic_21_icon',
                'banner_image_link' => 'topic_21_banner',
            ],
            [
                'owner_id' => User::all()->random()['id'],
                'name' => 'Spongebob Squarepants',
                'genre_id' => 3,
                'description' => 'Underwater laughs and quotes.',
                'icon_image_link' => 'topic_22_icon',
                'banner_image_link' => 'topic_22_banner',
            ],
            [
                'owner_id' => User::all()->random()['id'],
                'name' => 'Avatar: The Last Airbender',
                'genre_id' => 3,
                'description' => 'Bending elements and deep lore.',
                'icon_image_link' => 'topic_23_icon',
                'banner_image_link' => 'topic_23_banner',
            ],
            [
                'owner_id' => User::all()->random()['id'],
                'name' => 'Demon Slayer',
                'genre_id' => 3,
                'description' => 'Demon hunting and breathing styles.',
                'icon_image_link' => 'topic_24_icon',
                'banner_image_link' => 'topic_24_banner',
            ],
            [
                'owner_id' => User::all()->random()['id'],
                'name' => 'Adventure Time',
                'genre_id' => 3,
                'description' => 'Ooo, Finn, and the Land beyond.',
                'icon_image_link' => 'topic_25_icon',
                'banner_image_link' => 'topic_25_banner',
            ],
            [
                'owner_id' => User::all()->random()['id'],
                'name' => 'Bojack Horseman',
                'genre_id' => 3,
                'description' => 'Hollywood satire and personal struggles.',
                'icon_image_link' => 'topic_26_icon',
                'banner_image_link' => 'topic_26_banner',
            ],
            [
                'owner_id' => User::all()->random()['id'],
                'name' => 'Studio Ghibli Talk',
                'genre_id' => 3,
                'description' => 'Exploring the worlds of Miyazaki.',
                'icon_image_link' => 'topic_27_icon',
                'banner_image_link' => 'topic_27_banner',
            ],
            [
                'owner_id' => User::all()->random()['id'],
                'name' => 'Indie Animation',
                'genre_id' => 3,
                'description' => 'Celebrating non-mainstream gems.',
                'icon_image_link' => 'topic_28_icon',
                'banner_image_link' => 'topic_28_banner',
            ],
            [
                'owner_id' => User::all()->random()['id'],
                'name' => 'Rocket Science',
                'genre_id' => 4,
                'description' => 'Orbit mechanics to propulsion.',
                'icon_image_link' => 'topic_29_icon',
                'banner_image_link' => 'topic_29_banner',
            ],
            [
                'owner_id' => User::all()->random()['id'],
                'name' => 'Programming Concepts',
                'genre_id' => 4,
                'description' => 'Discussing programming principles.',
                'icon_image_link' => 'topic_30_icon',
                'banner_image_link' => 'topic_30_banner',
            ],
            [
                'owner_id' => User::all()->random()['id'],
                'name' => 'Medieval History',
                'genre_id' => 4,
                'description' => 'Castles, knights, and crusades.',
                'icon_image_link' => 'topic_31_icon',
                'banner_image_link' => 'topic_31_banner',
            ],
            [
                'owner_id' => User::all()->random()['id'],
                'name' => 'Paleontology',
                'genre_id' => 4,
                'description' => 'Dinosaurs, fossils, and ancient life.',
                'icon_image_link' => 'topic_32_icon',
                'banner_image_link' => 'topic_32_banner',
            ],
            [
                'owner_id' => User::all()->random()['id'],
                'name' => 'Quantum Physics',
                'genre_id' => 4,
                'description' => 'The weird world of particles.',
                'icon_image_link' => 'topic_33_icon',
                'banner_image_link' => 'topic_33_banner',
            ],
            [
                'owner_id' => User::all()->random()['id'],
                'name' => 'Environmental Science',
                'genre_id' => 4,
                'description' => 'Climate change and ecosystems.',
                'icon_image_link' => 'topic_34_icon',
                'banner_image_link' => 'topic_34_banner',
            ],
            [
                'owner_id' => User::all()->random()['id'],
                'name' => 'Philosophy 101',
                'genre_id' => 4,
                'description' => 'Debates, theories, and thought experiments.',
                'icon_image_link' => 'topic_35_icon',
                'banner_image_link' => 'topic_35_banner',
            ],
            [
                'owner_id' => User::all()->random()['id'],
                'name' => 'World Religions',
                'genre_id' => 4,
                'description' => 'Exploring beliefs and faiths.',
                'icon_image_link' => 'topic_36_icon',
                'banner_image_link' => 'topic_36_banner',
            ],
            [
                'owner_id' => User::all()->random()['id'],
                'name' => 'Language Learning',
                'genre_id' => 4,
                'description' => 'Grammar tips, vocab, and immersion.',
                'icon_image_link' => 'topic_37_icon',
                'banner_image_link' => 'topic_37_banner',
            ],
            [
                'owner_id' => User::all()->random()['id'],
                'name' => 'College Survival Guide',
                'genre_id' => 4,
                'description' => 'Study hacks and college life advice.',
                'icon_image_link' => 'topic_38_icon',
                'banner_image_link' => 'topic_38_banner',
            ],
            [
                'owner_id' => User::all()->random()['id'],
                'name' => 'Global Headlines',
                'genre_id' => 5,
                'description' => 'Discussing current world news.',
                'icon_image_link' => 'topic_39_icon',
                'banner_image_link' => 'topic_39_banner',
            ],
            [
                'owner_id' => User::all()->random()['id'],
                'name' => 'Local Issues',
                'genre_id' => 5,
                'description' => 'Community-level problems and insights.',
                'icon_image_link' => 'topic_40_icon',
                'banner_image_link' => 'topic_40_banner',
            ],
            [
                'owner_id' => User::all()->random()['id'],
                'name' => 'Policy and Law',
                'genre_id' => 5,
                'description' => 'Regulations, rights, and policy-making.',
                'icon_image_link' => 'topic_41_icon',
                'banner_image_link' => 'topic_41_banner',
            ],
            [
                'owner_id' => User::all()->random()['id'],
                'name' => 'Election Watch',
                'genre_id' => 5,
                'description' => 'Covering election seasons globally.',
                'icon_image_link' => 'topic_42_icon',
                'banner_image_link' => 'topic_42_banner',
            ],
            [
                'owner_id' => User::all()->random()['id'],
                'name' => 'Media Literacy',
                'genre_id' => 5,
                'description' => 'Spotting bias, fake news, and disinfo.',
                'icon_image_link' => 'topic_43_icon',
                'banner_image_link' => 'topic_43_banner',
            ],
            [
                'owner_id' => User::all()->random()['id'],
                'name' => 'Conflict Zones',
                'genre_id' => 5,
                'description' => 'Understanding war and unrest areas.',
                'icon_image_link' => 'topic_44_icon',
                'banner_image_link' => 'topic_44_banner',
            ],
            [
                'owner_id' => User::all()->random()['id'],
                'name' => 'Economic Politics',
                'genre_id' => 5,
                'description' => 'Money and policy intersections.',
                'icon_image_link' => 'topic_45_icon',
                'banner_image_link' => 'topic_45_banner',
            ],
            [
                'owner_id' => User::all()->random()['id'],
                'name' => 'Human Rights Talk',
                'genre_id' => 5,
                'description' => 'Discussing justice and advocacy.',
                'icon_image_link' => 'topic_46_icon',
                'banner_image_link' => 'topic_46_banner',
            ],
        ]);
    }
}
